name: Solver application

on:
  push:
    tags:
      - "*"

jobs:
  build_source:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v3

      - name: Configure solver
        working-directory: solver_application/
        run: |
          cmake -S ./ -B ./build -DCPACK_PACKAGE_VERSION=${{github.ref_name}}

      - name: Build solver
        working-directory: solver_application/build/
        run: |
          make package_source
        
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}

  build_linux:
    runs-on: ubuntu-latest
    needs: build_source
    steps:
      - uses: actions/checkout@v3

      - name: Configure solver
        working-directory: solver_application/
        run: |
          cmake -S ./ -B ./build -DCPACK_PACKAGE_VERSION=${{github.ref_name}}

      - name: Build solver
        working-directory: solver_application/build/
        run: |
          make package

      - name: Update release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.build_source.outputs.upload_url }}
          asset_name: Solver-${{github.ref_name}}.deb
          asset_path: ./solver_application/build/Solver-${{github.ref_name}}.deb
          asset_content_type: application/deb

  build_windows:
    runs-on: windows-latest
    needs: build_source
    steps:
      - uses: actions/checkout@v3

      - name: Configure solver
      - working-directory: solver_application/
        run: |
          cmake -S ./ -B ./build -DCPACK_PACKAGE_VERSION=${{github.ref_name}}

      - name: Build solver
        working-directory: solver_application/
        run: |
          cmake --build ./build

      - name: Update release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.build_source.outputs.upload_url }}
          asset_name: Solver-${{github.ref_name}}.exe
          asset_path: ./solver_application/build/solver.exe
          asset_content_type: application/exe

  build_macos:
    runs-on: macos-latest
    needs: build_source
    steps:
      - uses: actions/checkout@v3

      - name: Configure solver
        working-directory: solver_application/
        run: |
          cmake -S ./ -B ./build -DCPACK_PACKAGE_VERSION=${{github.ref_name}}

      - name: Build solver
        working-directory: solver_application/build/
        run: |
          make package

      - name: Update release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.build_source.outputs.upload_url }}
          asset_name: Solver-${{github.ref_name}}.dmg
          asset_path: ./solver_application/build/Solver-${{github.ref_name}}.dmg
          asset_content_type: application/dmg